#!/bin/bash

# config
RST_MASTER="https://code.cor-lab.de/git/rst.git.proto.git"
RST_CSRA="https://projects.cit-ec.uni-bielefeld.de/git/lsp-csra.rst-csra.git"
MASTER_BRANCH="0.14"
CSRA_BRANCH="$MASTER_BRANCH"
DESTINATION="$(pwd)"
TMPDIR=${TMPDIR-/tmp}
TMP="$TMPDIR/rst-experimental-$(date +%s%N | cut -b1-13)"

set -e

# prepare environment
mkdir -p "$TMP"
cd "$TMP"
git init rst
cd rst
git remote add master "$RST_MASTER"
git remote add csra "$RST_CSRA"
git fetch --all
git checkout "csra/$CSRA_BRANCH"

MASTER_REV="$(git rev-parse master/$MASTER_BRANCH | cut -b1-8)"
FORK_REV="$(git rev-parse HEAD | cut -b1-8)"

echo "Deleting all files from proto:"
find "$DESTINATION/proto" -type f -name "*proto" -print0 | xargs -0 rm

NEW_FILES="$(git diff --name-only --diff-filter=A "master/${MASTER_BRANCH}" proto/sandbox)"

echo "Adding new files:"
for NEW in $NEW_FILES; do
  echo " + $NEW"
  NEW_NAME="${NEW/sandbox/experimental}"
  DST_DIR="$(dirname "${DESTINATION}/${NEW_NAME}")"
  mkdir -p "$DST_DIR"
  cp "$NEW" "$DESTINATION/$NEW_NAME"
done

NEW_FILES_STABLE="$(git diff --name-only --diff-filter=A "master/${MASTER_BRANCH}" proto/stable)"
if [ "$NEW_FILES_STABE" != "" ]; then
  echo "Ignoring new files in stable:"
  for NEW in $NEW_FILES_STABLE; do
    echo " - $NEW"
  done
fi

CHANGED_FILES="$(git diff --name-only --diff-filter=DM "master/${MASTER_BRANCH}" proto)"
if [ "$CHANGED_FILES" != "" ]; then
  echo "Ignoring changes in:"
  for NEW in $CHANGED_FILES; do
    echo " * $NEW"
  done
fi

cd "$DESTINATION"
shopt -s globstar
git add proto/**proto
git commit -m "Reset to diff btw master=${MASTER_REV} and fork=${FORK_REV}."

rm -rf "$TMP"

