# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rst/guidelight/PathControl.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rst/guidelight/PathControl.proto',
  package='rst.guidelight',
  syntax='proto2',
  serialized_pb=_b('\n rst/guidelight/PathControl.proto\x12\x0erst.guidelight\"\xd9\x01\n\x0bPathControl\x12>\n\npath_state\x18\x01 \x02(\x0e\x32*.rst.guidelight.PathControl.LightbandState\x12\x12\n\nstart_node\x18\x02 \x01(\r\x12\x11\n\tdest_node\x18\x03 \x01(\r\x12\x13\n\x08priority\x18\x04 \x01(\r:\x01\x30\"N\n\x0eLightbandState\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x07\n\x03OFF\x10\x01\x12\x06\n\x02ON\x10\x02\x12\t\n\x05GUIDE\x10\x03\x12\t\n\x05\x42LINK\x10\x04\x12\x08\n\x04\x45VAC\x10\x05\x42\x11\x42\x0fPathControlType')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_PATHCONTROL_LIGHTBANDSTATE = _descriptor.EnumDescriptor(
  name='LightbandState',
  full_name='rst.guidelight.PathControl.LightbandState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
    name='UNKNOWN', index=0, number=0,
    options=None,
    type=None),
    _descriptor.EnumValueDescriptor(
    name='OFF', index=1, number=1,
    options=None,
    type=None),
    _descriptor.EnumValueDescriptor(
    name='ON', index=2, number=2,
    options=None,
    type=None),
    _descriptor.EnumValueDescriptor(
    name='GUIDE', index=3, number=3,
    options=None,
    type=None),
    _descriptor.EnumValueDescriptor(
    name='BLINK', index=4, number=4,
    options=None,
    type=None),
    _descriptor.EnumValueDescriptor(
    name='EVAC', index=5, number=5,
    options=None,
    type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=192,
  serialized_end=270,
)
_sym_db.RegisterEnumDescriptor(_PATHCONTROL_LIGHTBANDSTATE)


_PATHCONTROL = _descriptor.Descriptor(
  name='PathControl',
  full_name='rst.guidelight.PathControl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
    name='path_state', full_name='rst.guidelight.PathControl.path_state', index=0,
    number=1, type=14, cpp_type=8, label=2,
    has_default_value=False, default_value=0,
    message_type=None, enum_type=None, containing_type=None,
    is_extension=False, extension_scope=None,
    options=None),
    _descriptor.FieldDescriptor(
    name='start_node', full_name='rst.guidelight.PathControl.start_node', index=1,
    number=2, type=13, cpp_type=3, label=1,
    has_default_value=False, default_value=0,
    message_type=None, enum_type=None, containing_type=None,
    is_extension=False, extension_scope=None,
    options=None),
    _descriptor.FieldDescriptor(
    name='dest_node', full_name='rst.guidelight.PathControl.dest_node', index=2,
    number=3, type=13, cpp_type=3, label=1,
    has_default_value=False, default_value=0,
    message_type=None, enum_type=None, containing_type=None,
    is_extension=False, extension_scope=None,
    options=None),
    _descriptor.FieldDescriptor(
    name='priority', full_name='rst.guidelight.PathControl.priority', index=3,
    number=4, type=13, cpp_type=3, label=1,
    has_default_value=True, default_value=0,
    message_type=None, enum_type=None, containing_type=None,
    is_extension=False, extension_scope=None,
    options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PATHCONTROL_LIGHTBANDSTATE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=270,
)

_PATHCONTROL.fields_by_name['path_state'].enum_type = _PATHCONTROL_LIGHTBANDSTATE
_PATHCONTROL_LIGHTBANDSTATE.containing_type = _PATHCONTROL
DESCRIPTOR.message_types_by_name['PathControl'] = _PATHCONTROL

PathControl = _reflection.GeneratedProtocolMessageType('PathControl', (_message.Message,), dict(
  DESCRIPTOR = _PATHCONTROL,
  __module__ = 'rst.guidelight.PathControl_pb2'
  # @@protoc_insertion_point(class_scope:rst.guidelight.PathControl)
  ))
_sym_db.RegisterMessage(PathControl)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('B\017PathControlType'))
# @@protoc_insertion_point(module_scope)
